Router.route('/nctypes',           { name: 'nctypes' })
Router.route('/nctypes/new',       { name: 'nctypeNew' })
Router.route('/nctypes/add',       { name: 'nctypeNewForNonconformity' })
Router.route('/nctypes/:_id',      { name: 'nctype', controller: 'NcTypeController' })
Router.route('/nctypes/:_id/edit', { name: 'nctypeEdit', controller: 'NcTypeController' })
