Router.route('/nonconformities/p/:limit?',       { name: 'nonconformities' })
Router.route('/nonconformities/closed/:limit?',  { name: 'nonconformitiesClosed' })
Router.route('/nonconformities/new',             { name: 'nonconformityNew' })
Router.route('/nonconformities/:_id',            { name: 'nonconformity' })
Router.route('/nonconformities/:_id/edit',       { name: 'nonconformityEdit' })
