Router.route('/origins/p',           { name: 'origins' })
Router.route('/origins/new',       { name: 'originNew' })
Router.route('/origins/add',       { name: 'originNewForNonconformity' })
Router.route('/origins/:_id',      { name: 'origin', controller: 'OriginController' })
Router.route('/origins/:_id/edit', { name: 'originEdit', controller: 'OriginController' })
