Router.route('/nonconformities/p/:limit?',       { name: 'conformities' })
Router.route('/nonconformities/closed/:limit?',  { name: 'conformitiesClosed' })
Router.route('/nonconformities/new',             { name: 'conformityNew' })
Router.route('/nonconformities/:_id',            { name: 'conformity' })
Router.route('/nonconformities/:_id/edit',       { name: 'conformityEdit' })
