Router.route('/maintenances/p/:limit?', { name: 'maintenances' })
Router.route('/maintenances/new',       { name: 'maintenanceNew' })
Router.route('/maintenances/reports',   { name: 'maintenanceReports' })
Router.route('/maintenances/status',    { name: 'maintenanceStatus' })
Router.route('/maintenances/:_id',      { name: 'maintenance' })
Router.route('/maintenances/:_id/edit', { name: 'maintenanceEdit', controller: 'MaintenanceController' })
