Router.route('/settings/new',       { name: 'settingNew' })
Router.route('/settings/:_id',      { name: 'setting' })
Router.route('/settings/:_id/edit', { name: 'settingEdit', controller: 'SettingController' })
Router.route('/digitalSignature/:_id',     { name: 'digitalSignature', controller: 'SettingController' })
Router.route('/digitalSignature/:_id/edit',{ name: 'digitalSignatureEdit', controller: 'SettingController' })
Router.route('/_customOptions/:_id',     { name: 'customOptions', controller: 'SettingController' })
Router.route('/_customOptions/:_id/edit',{ name: 'customOptionsEdit', controller: 'SettingController' })
